apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - ../../../bases/www
    - ./ingress.yaml
    - ./pdb.yaml
patches:
    - path: ./patches/www.yaml
configMapGenerator:
    - name: deploy-config
      envs:
        - ./deploy-config.env
