apiVersion: apps/v1
kind: Deployment
metadata:
    name: hothouse
spec:
    minReadySeconds: 10
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0
    replicas: 2
    template:
        spec:
            nodeSelector:
                kubernetes.io/arch: amd64
            terminationGracePeriodSeconds: 30
            containers:
                - name: hothouse
                  tty: true
                  envFrom:
                    - configMapRef:
                        name: deploy-config
                  env:
                      - name: NODE_ENV
                        value: production
                      - name: NEXT_PUBLIC_APP_ENV
                        value: prod
                  resources:
                      requests:
                          cpu: 500m
                          memory: 2000Mi
