apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - ../../bases/worker
    - redis.yaml

secretGenerator:
    - name: hothouse
      envs:
          - secrets/secrets.plain

configMapGenerator:
    - name: system-prompt
      files:
          - ./files/CANDIDATE.md

patches:
    - path: ./worker.yaml
