apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - ../../bases/www
    - redis.yaml
secretGenerator:
    - name: hothouse
      envs:
          - secrets/secrets.plain
patches:
    - path: ./www.yaml