---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: master
          image: redis:7
          imagePullPolicy: IfNotPresent
          command:
            ["docker-entrypoint.sh", "redis-server", "--appendonly", "yes"]
          resources: { requests: { cpu: 50m, memory: 100Mi } }
          ports:
            - containerPort: 6379
          env:
            - name: TZ
              value: UTC
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
