apiVersion: apps/v1
kind: Deployment
metadata:
    name: hothouse-worker
spec:
    template:
        spec:
            terminationGracePeriodSeconds: 3
            volumes:
                - name: system-prompt
                  configMap:
                      name: system-prompt
            containers:
                - name: hothouse-worker
                  env:
                      - name: NODE_ENV
                        value: development
                      - name: REDIS_SERVERS
                        value: redis:6379
                      - name: LOG_LEVEL
                        value: debug
                  envFrom:
                      - secretRef:
                            name: hothouse
                  volumeMounts:
                      - name: system-prompt
                        mountPath: /app/CANDIDATE.md
                        subPath: CANDIDATE.md
                  command:
                    -  ./node_modules/.bin/tsx
                    - "watch"
                    - "--no-cache"
                    - "--exclude=node_modules"
                    - "--clear-screen=false"
                    - "--no-deprecation"
                    - "--trace-warnings"
                    - "--inspect=0.0.0.0:9229"
                    - "--dns-result-order=ipv4first"
                    - "worker/index.ts"