apiVersion: apps/v1
kind: Deployment
metadata:
    name: hothouse-worker
spec:
    template:
        spec:
            terminationGracePeriodSeconds: 3
            containers:
                - name: hothouse-worker
                  env:
                      - name: NODE_ENV
                        value: development
                      - name: REDIS_SERVERS
                        value: redis:6379
                  envFrom:
                      - secretRef:
                            name: hothouse