apiVersion: apps/v1
kind: Deployment
metadata:
    name: hothouse
spec:
    template:
        spec:
            terminationGracePeriodSeconds: 3
            containers:
                - name: hothouse
                  env:
                      - name: NODE_ENV
                        value: development
                      - name: REDIS_SERVERS
                        value: redis:6379
                      - name: LOG_LEVEL
                        value: debug
                  envFrom:
                      - secretRef:
                            name: hothouse
